accounts/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('account_activation_sent/', views.account_activation_sent.as_view(), name='account_activation_sent'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('activated/', views.activated.as_view(), name='activated'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path("",include('blog.urls', namespace='blog')),
]

blog/urls.py
from . import views
from django.urls import path,include
from django.contrib.auth import views as auth_views

app_name = 'blog'
urlpatterns = [
    path("",views.PostList.as_view(),name = 'home'),
    path('create/', views.create_blog, name='create_view'),
    path("<int:id>/",views.post_detail,name = 'post_detail'),
    path("draft/<int:id>/",views.draft_detail,name = 'draft'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('blog.urls', namespace='blog')),
    path("accounts/",include('accounts.urls')),
]

templates/draft_detail.html
{% extends 'base.html' %} {% block content %}
<style>
  body{
  font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #F9EBEA;
  }
  .card {
        box-shadow: 0 16px 48px #E3E7EB;
         margin: 0 auto;
          float: none;
           margin-bottom: px;
    }

</style>
<div class="col-md-4 card mb-4  mt-3 ">
      <div class="card-body">
        <h1>Edit Blog</h1>
        {% load crispy_forms_tags %}
        <form method="post" style="margin-top: 1.3em;">
          {{ form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg" style="margin-left:auto;margin-right:auto;display:block;margin-top:5%;margin-bottom:0%">Create</button>
        </form>
           <a href="{% url 'accounts:profile' username=user.username %}"  style="text-align: right;
    float: right;">Profile</a>
      </div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #F9EBEA;

    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to Channel!</h3>
                    <p class="text-light">Read Blogs about everyday life. &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'blog:post_detail' post.id  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>

{% if is_paginated %}
  <nav aria-label="Page navigation conatiner"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

    {% endif %}
  </ul>
  </nav>
</div>
{% endif %}
{%endblock%}

templates/post_detail.html
{% extends 'base.html' %} {% block content %}
<style>
  body{
  font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #F9EBEA;
  }

</style>
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        {% if user.is_authenticated %}
        <a href="{% url 'blog:draft' id=post.id %}"  style="text-align: right;
    float: right;">Edit</a>
        {% endif %}
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ comments.count }} comments</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">

        <h3>Leave a comment</h3>
        {% load crispy_forms_tags %}
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    {% if user.is_authenticated %}
    <div class="card-body">
        <p class="card-text"> {{ user.first_name }} make a blog?</p>
        <a href="{% url 'blog:create_view' %}"
           class="btn btn-success">create!</a>
    </div>
    {% else %}
    <div class="card-body">
        <p class="card-text"> Do you want to make a blog?</p>
        <a href="{% url 'accounts:signup' %}"
           class="btn btn-info">Know more!</a>
    </div>
    {% endif %}
</div>
</div>

{% endblock sidebar %}